#**Welcome to Numpy Tut**

In [3]:
import numpy as np

In [4]:
myarr = np.array([3,6,32,7], np.int8)

In [5]:
myarr

array([ 3,  6, 32,  7], dtype=int8)

In [6]:
myarr.dtype


dtype('int8')

**Array creation : Conversion from python structures**

In [8]:
listarr = np.array([[1,2,3],[5,8,5],[0,2,3]])

In [10]:
listarr

array([[1, 2, 3],
       [5, 8, 5],
       [0, 2, 3]])

In [11]:
listarr.shape


(3, 3)

In [12]:
listarr.size

9

In [13]:
np.array({34,54,90})

array({34, 90, 54}, dtype=object)

#**Intrinsic Numpy array creatin**

In [14]:
zeros = np.zeros((2,5))


In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
zeros.shape

(2, 5)

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
lspace = np.linspace(1,50,10)

In [23]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [25]:
emp = np.empty([4,6])


In [26]:
emp


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
emp_like = np.empty_like(lspace)


In [28]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [30]:
ide = np.identity(45)

In [31]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [32]:
arr = np.arange(99)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr = arr.ravel()

In [38]:
arr.shape

(99,)

In [39]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [40]:
ar = np.array(x)

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [42]:
ar.sum(axis = 0)

array([12,  8,  9])

In [43]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [44]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [45]:
ar.flat

In [47]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [48]:
ar.ndim

2

In [49]:
ar.size

9

In [50]:
ar.nbytes

72

In [51]:
one = np.array([1,2,4,67,89])

In [52]:
one.argmax()

np.int64(4)

In [53]:
one.argmin()

np.int64(0)

In [54]:
one.argsort()

array([0, 1, 2, 3, 4])

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [57]:
ar.argmin(axis = 0)

array([0, 2, 2])

In [60]:
ar.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 1, 0]])

In [61]:
ar2 = np.array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [62]:
s = ar + ar2

In [63]:
s

array([[ 2,  6, 10],
       [ 6, 10,  7],
       [10,  7,  0]])

In [64]:
ar * ar2

array([[ 1,  8, 21],
       [ 8, 25,  6],
       [21,  6,  0]])

In [65]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [66]:
ar.sum()

np.int64(29)

In [67]:
ar.max()

np.int64(7)

In [68]:
ar.min()

np.int64(0)

In [69]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [70]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [71]:
type(np.where(ar>5))

tuple

In [72]:
np.count_nonzero(ar)

np.int64(8)

In [74]:
ar[1,2] = 0

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [76]:
import sys

In [78]:
py_ar = [0,4,55,2]

In [79]:
np_ar = np.array(py_ar)

In [80]:
sys.getsizeof(1) * len(py_ar)

112

In [81]:
np_ar.itemsize * np_ar.size

32

In [82]:
np_ar.tolist()

[0, 4, 55, 2]